-- El personal de la empresa que ejerce de tutor del alumnado en practicas. Es
-- una lista y no tres columnas mas en `empresa` porque una empresa puede tener
-- varios, y quien tutoriza a cada alumno se elige al asignarle la empresa.
--
-- No sustituye al contacto de la empresa (`empresa.contacto_*`), que sigue
-- siendo el administrativo: quien firma el convenio no tiene por que ser quien
-- esta con el alumno en el taller.
CREATE TABLE tutor_empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa(id),
    nombre VARCHAR(255) NOT NULL,
    cargo VARCHAR(255),
    telefono VARCHAR(255),
    correo VARCHAR(255)
);

CREATE INDEX idx_tutor_empresa ON tutor_empresa(empresa_id);

-- Nullable: una asignacion puede no tener tutor de empresa, y borrar un tutor
-- de la ficha deja a los suyos sin el en vez de bloquear el borrado.
ALTER TABLE asignacion ADD COLUMN tutor_empresa_id BIGINT REFERENCES tutor_empresa(id);
