CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) NOT NULL,
    contrasena_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    es_admin BOOLEAN NOT NULL DEFAULT FALSE,
    debe_cambiar_contrasena BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMP WITH TIME ZONE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuario_correo UNIQUE (correo)
);

CREATE TABLE correo_permitido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) NOT NULL,
    CONSTRAINT uk_correo_permitido_correo UNIQUE (correo)
);
