CREATE TABLE empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(2000),
    imagen VARCHAR(255),
    direccion VARCHAR(255),
    sector_id BIGINT NOT NULL REFERENCES etiqueta(id),
    observaciones VARCHAR(2000),
    contacto_nombre VARCHAR(255),
    contacto_telefono VARCHAR(255),
    contacto_email VARCHAR(255),
    publicada BOOLEAN NOT NULL DEFAULT FALSE,
    creada_por_id BIGINT NOT NULL REFERENCES usuario(id),
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE empresa_etiqueta (
    empresa_id BIGINT NOT NULL REFERENCES empresa(id),
    etiqueta_id BIGINT NOT NULL REFERENCES etiqueta(id),
    PRIMARY KEY (empresa_id, etiqueta_id)
);
