CREATE TABLE asignacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES usuario(id),
    empresa_id BIGINT NOT NULL REFERENCES empresa(id),
    tutor_centro_id BIGINT NOT NULL REFERENCES usuario(id),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (alumno_id, empresa_id)
);
