CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES usuario(id),
    autor_id BIGINT NOT NULL REFERENCES usuario(id),
    empresa_id BIGINT NOT NULL REFERENCES empresa(id),
    contenido TEXT NOT NULL,
    calificacion INT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    moderada_por_id BIGINT REFERENCES usuario(id),
    motivo_rechazo TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_moderacion TIMESTAMP WITH TIME ZONE,
    UNIQUE (alumno_id, empresa_id)
);
