resolver 127.0.0.11 valid=30s;

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        set $backend_upstream backend:8080;
        proxy_pass http://$backend_upstream/api/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
