spring.application.name=practikalia
spring.jpa.hibernate.ddl-auto=validate

app.uploads-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.review.calificacion-min=${REVIEW_CALIFICACION_MIN:1}
app.review.calificacion-max=${REVIEW_CALIFICACION_MAX:5}
